[package]
name = "jmap_sieve"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
jmap = { path = "../jmap" }
store = { path = "../store" }
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"

[features]
debug = []
